SkyKotApp/SkyKotApp/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KotClassLibrary.Models;
using SkyKotApp.Data;
using Microsoft.AspNetCore.Authorization;
using SkyKotApp.Data.Default;
using System.Security.Claims;
using SkyKotApp.Services.General;
using KotClassLibrary.ViewModels.HouseVM;

namespace SkyKotApp.Controllers
{
    [Authorize(Roles = Roles.Admin + ", " + Roles.Owner)]
    public class HouseController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ISkyKotRepository skyKotRepository;

        public HouseController(AppDbContext context, ISkyKotRepository skyKotRepository)
        {
            _context = context;
            this.skyKotRepository = skyKotRepository;
        }

        // GET: House
        public async Task<IActionResult> Index()
        {
            //var userRole = User.FindFirstValue(ClaimTypes.Role);
           
            return View(await skyKotRepository.GetHouses());
        }

        // GET: House/Details/5
        public async Task<IActionResult> Details(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            if(skyKotRepository.GetCurrentUserRole() == Roles.Owner)
            {
                //check if is owner of the house
                if(!await skyKotRepository.IsOwnHouseAsync(id))
                {
                    return NotFound();
                }
            }

            var house = await skyKotRepository.GetHouse(id);
            if (house == null)
            {
                return NotFound();
            }

            return View(house);
        }

        // GET: House/Create
        public async Task<IActionResult> CreateAsync()
        {
            HouseCreateViewModel model = new HouseCreateViewModel()
            {
                HouseSpecificationsList = await skyKotRepository.GetHouseSpecificationsToCreate(),
                HouseExpensesList = await skyKotRepository.GetHouseExpenseToCreate(),
            };
            ViewData["ZipCodeId"] = new SelectList(_context.ZipCodes, "ZipCodeId", "City");
            return View(model);
        }

        // POST: House/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Bind("HouseId,Name,ZipCodeId,StreetName,HouseNumber,Description")]
        public async Task<IActionResult> Create(HouseCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                await skyKotRepository.AddHouse(model);
                return RedirectToAction(nameof(Index));
            }
            model.HouseSpecificationsList = await skyKotRepository.GetHouseSpecificationsToCreate();
            model.HouseExpensesList = await skyKotRepository.GetHouseExpenseToCreate();
            ViewData["ZipCodeId"] = new SelectList(_context.ZipCodes, "ZipCodeId", "City", model.ZipCodeId);
            return View(model);
        }

        // GET: House/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
            {
                //check if is owner of the house
                if (!await skyKotRepository.IsOwnHouseAsync(id))
                {
                    return NotFound();
                }
            }

            var house = await skyKotRepository.GetHouse(id);
            if (house == null)
            {
                return NotFound();
            }

            HouseEditViewModel model = new HouseEditViewModel(house)
            {
                HouseSpecificationsList = await skyKotRepository.GetHouseSpecificationsToEdit(house.HouseSpecifications),
                HouseExpensesList = await skyKotRepository.GetHouseExpensesToEdit(house.HouseExpenses),
                ZipCodesSelectList = await skyKotRepository.GetZipCodesSelect()
            };
            return View(model);
        }

        // POST: House/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Bind("HouseId,Name,ZipCodeId,StreetName,HouseNumber,Description")]
        public async Task<IActionResult> Edit(int id, HouseEditViewModel model)
        {
            if (id != model.HouseId)
            {
                return NotFound();
            }

            if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
            {
                //check if is owner of the house
                if (!await skyKotRepository.IsOwnHouseAsync(id))
                {
                    return NotFound();
                }
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await skyKotRepository.UpdateHouse(model);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HouseExists(model.HouseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            model.HouseSpecificationsList = await skyKotRepository.GetHouseSpecificationsToEdit(model.HouseSpecifications);
            model.HouseExpensesList = await skyKotRepository.GetHouseExpensesToEdit(model.HouseExpenses);
            model.ZipCodesSelectList = await skyKotRepository.GetZipCodesSelect();
            return View(model);
        }

        // GET: House/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
            {
                //check if is owner of the house
                if (!await skyKotRepository.IsOwnHouseAsync(id))
                {
                    return NotFound();
                }
            }

            var house = await _context.Houses
                .Include(h => h.ZipCode)
                .FirstOrDefaultAsync(m => m.HouseId == id);
            if (house == null)
            {
                return NotFound();
            }

            return View(house);
        }

        // POST: House/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
            {
                //check if is owner of the house
                if (!await skyKotRepository.IsOwnHouseAsync(id))
                {
                    return NotFound();
                }
            }
            var house = await _context.Houses.FindAsync(id);
            _context.Houses.Remove(house);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HouseExists(int id)
        {
            return _context.Houses.Any(e => e.HouseId == id);
        }
    }
}

SkyKotApp/SkyKotApp/Controllers/UserController.cs
using KotClassLibrary.Helpers;
using KotClassLibrary.Models;
using KotClassLibrary.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SkyKotApp.Data.Default;
using SkyKotApp.Services.General;
using SkyKotApp.Services.Login;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace SkyKotApp.Controllers
{
    [Authorize(Roles = Roles.Admin + ", " + Roles.Owner)]
    public class UserController : Controller
    {
        private readonly ISkyKotRepository skyKotRepository;
        private readonly IWebHostEnvironment hostEnvironment;
        private readonly ILoginRepository loginRepository;

        public UserController(
            ISkyKotRepository skyKotRepository,
            IWebHostEnvironment hostEnvironment,
            ILoginRepository loginRepository)
        {
            this.skyKotRepository = skyKotRepository;
            this.hostEnvironment = hostEnvironment;
            this.loginRepository = loginRepository;
        }
        public async Task<IActionResult> Index()
        {
            string currentUserRole = skyKotRepository.GetCurrentUserRole();
            if (currentUserRole == Roles.Admin)
            {
                return View(await skyKotRepository.GetCustomUsers());
            }
            else if(currentUserRole == Roles.Owner)
            {
                return View(await skyKotRepository.GetOwnCustomUsers());
            }
            return NotFound();
            
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return RedirecToNotFound();
            }

            if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
            {
                //check is owner
                if (!await skyKotRepository.IsUserOwner(id))
                {
                    return RedirecToNotFound();
                }
            }

            var user = await skyKotRepository.GetUser(id);
            if (user == null)
            {
                return RedirecToNotFound();
            }

            return View(user);
        }

        #region Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var identityUser = new CustomUser()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    UserName = $"{model.LastName}_{model.FirstName}_{Guid.NewGuid()}" // make userNmae Unique
                };
                identityUser.ProfileImage = PhotoHelper.UploadProfilePhoto(hostEnvironment, model.Photo);

                if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
                {
                    identityUser.OwnerId = skyKotRepository.GetCurrentUserId();
                }

                var result = await loginRepository.CreateUser(identityUser, model.Password);

                if (result.Succeeded)
                {
                    if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
                    {
                        // add to renter role
                        await skyKotRepository.AddToRenterRole(identityUser);
                    }
                    else
                    {
                        await skyKotRepository.AddToRole(identityUser, Roles.NormalUser);
                    }
                    var token = await loginRepository.GenerateEmailConfirmationToken(identityUser);
                    var confirmationLink = Url.Action("ConfirmEmail", "Account",
                    new { userId = identityUser.Id, token = token }, Request.Scheme);

                    try
                    {
                        EmailHelper.SendInvatationEmail(identityUser.Email, confirmationLink);
                    }
                    catch (Exception)
                    {
                        //do nothing
                    }
                    //if current user is owner
                    if(skyKotRepository.GetCurrentUserRole() == Roles.Owner)
                    {
                        //add as role member
                        await skyKotRepository.AddToRenterRole(identityUser);
                    }
                    
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }
        #endregion

        #region Edit
        [Authorize(Roles = Roles.Admin)]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return RedirecToNotFound();
            }
            if(skyKotRepository.GetCurrentUserRole() == Roles.Owner)
            {
                //check is owner
                if (!await skyKotRepository.IsUserOwner(id))
                {
                    return RedirecToNotFound();
                }
            }

            CustomUser user = await skyKotRepository.GetUser(id);
            if (user == null)
            {
                return RedirecToNotFound();
            }
            UserEditViewModel model = new UserEditViewModel(user);
            model.RoleId = skyKotRepository.GetRoleName(user.Id);
            if (skyKotRepository.GetCurrentUserRole() == Roles.Admin)
            {
                model.RolesSelectList = skyKotRepository.GetRoles();
            }
            return View(model);
        }

        // POST: Gebruiker/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Admin)]
        public async Task<IActionResult> Edit(string id, UserEditViewModel model)
        {
            if (id != model.HelperId)
            {
                return RedirecToNotFound();
            }

            if (ModelState.IsValid)
            {
                if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
                {
                    //check is owner
                    if (!await skyKotRepository.IsUserOwner(id))
                    {
                        return RedirecToNotFound();
                    }
                }
                CustomUser user = null;
                try
                {
                    user = await skyKotRepository.GetUser(model.HelperId);

                    if(await skyKotRepository.IsAlredyEmailExist(model.Email,model.HelperId))
                    {
                        ModelState.AddModelError("Email", "Email Alredy Exit");
                        return View(model);
                    }

                    user.FirstName = model.FirstName;
                    user.LastName = model.LastName;
                    user.Email = model.Email;
                    if(skyKotRepository.GetCurrentUserRole() == Roles.Admin)
                    {
                        user.IsAllowToUseTheApp = model.IsAllowToUseTheApp;
                    }

                    if(model.Photo == null)
                    {
                        if(!string.IsNullOrEmpty(model.ExistingPhotoPath))
                        {
                            model.ProfileImage = model.ExistingPhotoPath;
                        }
                    }
                    else
                    {
                        user.ProfileImage = PhotoHelper.UploadProfilePhoto(hostEnvironment, model.Photo);
                        PhotoHelper.DeleteProfilePhoto(hostEnvironment, model.ExistingPhotoPath);
                    }
                    await skyKotRepository.UpdateUser(user);

                    if (skyKotRepository.GetCurrentUserRole() == Roles.Admin)
                    {
                        //update role
                        await skyKotRepository.UpdateRole(user, model.RoleId);
                    }
                    return RedirectToAction("Index");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (user == null)
                    {
                        return RedirecToNotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

            }
            return View(model);
        }
        #endregion

        #region Delete
        // GET: Gebruiker/Delete/5
        [Authorize(Roles = Roles.Admin)]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return RedirecToNotFound();
            }
            if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)
            {
                //check is owner
                if (!await skyKotRepository.IsUserOwner(id))
                {
                    return RedirecToNotFound();
                }
            }

            var gebruiker = await skyKotRepository.GetUser(id);
            if (gebruiker == null)
            {
                return RedirecToNotFound();
            }

            return View(gebruiker);
        }

        // POST: Gebruiker/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = Roles.Admin)]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (skyKotRepository.GetCurrentUserRole() == Roles.Owner)

SkyKotApp/SkyKotApp/Views/Shared/PartialLoginNav.cshtml
@inject SignInManager<CustomUser> signInManager;
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="#">Sky Kot</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-house-user"></i>@localizer["home-link"]</a>
	        </li>
	        <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Room" asp-action="Index"><i class="fa-solid fa-building"></i>@localizer["room-link"]</a>
	        </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fa-solid fa-key"></i>@localizer["privacy-link"]</a>
            </li>
            @if (signInManager.IsSignedIn(User))
            {
                @if (User.IsInRole(Roles.Renter))
                {  
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Renter" asp-action="Index"><i class="fa-solid fa-building-circle-arrow-right"></i>@localizer["renter-link"]</a>
                    </li>
                }
                @if (User.IsInRole(Roles.Admin) || User.IsInRole(Roles.Owner))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="House" asp-action="Index"><i class="fa-solid fa-house"></i>@localizer["house-link"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index"><i class="fa-solid fa-users"></i>@localizer["user-link"]</a>
                    </li>   
                        <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="RenterRoom" asp-action="Index"><i class="fa-solid fa-building-circle-arrow-right"></i>@localizer["renter-room-link"]</a>
                    </li>
                }
                @if (User.IsInRole(Roles.Admin))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="AcademicYear" asp-action="Index"><i class="fa-solid fa-calendar-days"></i>@localizer["academicyear-link"]</a>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Profile"><i class="fa-solid fa-user-check"></i>@localizer["profile-link"]</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout"><i class="fa-solid fa-arrow-right-from-bracket"></i>@localizer["logout-link"]</a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link" data-link="Login" asp-controller="account" asp-action="Login">
                        <i class="fa-solid fa-arrow-right-to-bracket"></i>@localizer["login-link"]
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-link="Register" asp-controller="account" asp-action="Register">
                        <i class="fa-solid fa-right-to-bracket"></i>@localizer["register-link"]
                    </a>
                </li>
            }
            <li class="nav-link">
                <partial name="_Culture" />
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" style="display: none">
          <input class="form-control mr-sm-2" type="search" disabled placeholder="@localizer["search-btn"]" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">@localizer["search-lbl"]</button>
        </form>
      </div>
</nav>

SkyKotApp/SkyKotApp/Views/Shared/PartialModal.cshtml
@model ICollection<RoomImage>

@{
    int roomId = Model.Any() ? Model.FirstOrDefault().RoomId : 0;
    var carouselId = ModalHelper.GetCarouselId(roomId);
    var modalCarouselId = ModalHelper.GetModalCarouselId(roomId);
    var modalId = ModalHelper.GetModalId(roomId);
}
 <div class="modal fade" id="@modalId" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close default-transition" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class="fa-solid fa-xmark text-white "></i></span>
                </button>
            </div>
            <div class="modal-body">

                <div id="@modalCarouselId" class="carousel slide text-center" data-ride="@modalCarouselId">
                    <div class="carousel-inner">
                        @if (Model.Any())
                        {
                            var teller2 = 0;
                            foreach (var image in Model)
                            {
                                    var img = "/images/Room/" + (image.Path ?? "default_room.jpg");
                                if (teller2 == 0)
                                {
                                    <div class="carousel-item active">
                                            <div class="custom-background" style="background-image: url('@img')"></div>
                                    </div>
                                }
                                else
                                {
                                    <div class="carousel-item">
                                            <div class="custom-background" style="background-image: url('@img')"></div>
                                    </div>
                                }
                                teller2++;
                            }   
                        }
                    </div>
                    <a class="carousel-control-prev ml-auto" href="#@modalCarouselId" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next mr-auto" href="#@modalCarouselId" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

SkyKotApp/SkyKotApp/Views/Shared/PartialRoomImages.cshtml
@model ICollection<RoomImage>

@if (Model != null && Model.Any())
{
    int roomId = Model.FirstOrDefault().RoomId;
    var carouselId = "carousel-" + roomId;
    var modalCarouselId = "modal-carousel-" +  roomId;
    var modalId = "Modal-" +  roomId;
<div>
    <div id="@carouselId" class="carousel slide col-12" data-ride="@modalCarouselId">
            <ol class="carousel-indicators">
                <li data-target="#@carouselId" data-slide-to="0" class="active"></li>
                @for(int i = 1; i < Model.Count(); i++)
                {
                    <li data-target="#@carouselId" data-slide-to="@i"></li>
                }
            </ol>
            <div class="carousel-inner">
            @{var teller3 = 0;}
            @foreach (var image in Model)
            {
                var img = "/images/Room/" + (image.Path ?? "avatar.png");
                if (teller3 == 0)
                {
                    <div style="cursor:pointer;" class="carousel-item active" data-toggle="modal" data-target="#@modalId">
                         <div data-target="#@modalCarouselId" data-slide-to=@teller3 class="custom-background" style="cursor:pointer; border-radius: 10px;height: 80vh; width: 100%; background-image: url('@img')"></div>
                    </div>
                }
                else
                {
                    <div style="cursor:pointer;" class="carousel-item" data-toggle="modal" data-target="#@modalId">
                        <div data-target="#@modalCarouselId" data-slide-to=@teller3 class="custom-background" style="cursor:pointer; border-radius: 10px;height: 80vh; width: 100%; background-image: url('@img')"></div>
                    </div>
                }
                teller3++;

            }
        </div>
        <a class="carousel-control-prev" href="#@carouselId" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#@carouselId" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="col-12 d-none d-md-block d-lg-block d-xl-block">
        <div class="row justify-content-center" id="gallery" data-toggle="carousel2" data-target="#@carouselId">
            @{var teller = 0;}
            @foreach (var image in Model)
            {

                var img = "/images/Room/" + (image.Path ?? "default_room.jpg");

                <div class="m-2">
                    <div class="custom-background" style="cursor:pointer; border-radius: 10px; height:100px; width:100px; background-image: url('@img')"  data-target="#@carouselId" data-slide-to=@teller></div>
                </div>

                teller++;
            }
        </div>
    </div>
</div>
<partial name="PartialModal" model="@Model"/>
}

SkyKotApp/SkyKotApp/Views/Shared/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions

@{
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedCultures.Select(x => new SelectListItem { Value = x.Name, Text = localizer.GetString(x.Name)}).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"{Context.Request.Path.Value}{Context.Request.QueryString}";
}
<div style="display: none">
    <form method="post" asp-controller="Home" asp-action="CultureManagement" asp-route-returnUrl="@returnUrl">
        <select class="form-select" aria-label="Language"
            name="Culture" asp-for="@culture.RequestCulture.UICulture.Name"
            asp-items="cultureList"
            onchange="this.form.submit();"
            >

        </select>
    </form>
</div>

SkyKotApp/SkyKotApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - SkyKotApp</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
        *@
        <link rel="stylesheet" href="~/css/User.css" />
        @if (IsSectionDefined("Style"))
        {
            @RenderSection("Style", required: true);
        }
        <base href="~/" />
    </head>
    <body>
        <header>
           <partial name="PartialLoginNav"/>
        </header>
        <div class="container" style="padding-top: 15px">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <!-- Import Blazor Server JavaScript here -->
        <script src="_framework/blazor.server.js"></script>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - SkyKotApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/fontawesome-file.js"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>